/*
 * File: app/view/loginform.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.loginform', {
    extend: 'Ext.form.Panel',

    height: 136,
    id: 'loginform',
    width: 305,
    layout: {
        align: 'center',
        pack: 'center',
        type: 'vbox'
    },
    bodyPadding: 10,
    title: 'login with your domain account',
    method: 'POST',
    url: 'login.php',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            method: 'POST',
            url: 'login.php'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'username',
                    name: 'username'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'password',
                    name: 'password',
                    inputType: 'password'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var form = this.up('form').getForm(); // get the basic form
                        if (form.isValid()) { // make sure the form contains valid data before submitting
                            form.submit({
                                success: function(form, action) {

                                    form.owner.hide();

                                    var mainview=new Ext.create('MyApp.view.fileexplorer');
                                    mainview.show();
                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('Failed', action.result.msg);
                                }
                            });
                        }
                    },
                    text: 'login'
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onLoginformAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onLoginformAfterRender: function(component, eOpts) {
        this.center();
    }

});